---
- name: Install CLI tools
  hosts: all
  gather_facts: true

  vars_files:
    - ../../../default.config.yml
  vars:
    brew_path: /home/linuxbrew/.linuxbrew/bin

  pre_tasks: []

  roles: []

  tasks: 
    - name: Is Homebrew installed?
      stat:
        path: "{{ brew_path }}/brew"
      register: homebrew_bin

    - name: Install Homebrew
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: not homebrew_bin.stat.exists

    - name: Add Homebrew Path
      shell:  |
        (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> "/home/{{ ansible_env.USER }}/.bash_profile"
        (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> "/home/{{ ansible_env.USER }}/.zshrc"
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      when: not homebrew_bin.stat.exists

    - name: Install build tools
      ansible.builtin.package:
        name: "build-essential"
        state: present
      become: yes

    - name: Install notifier
      ansible.builtin.package:
        name: "libnotify-bin"
        state: present
      become: yes

    - name: Install GCC
      community.general.homebrew:
        name: gcc
        state: present

    - name: Install Docker
      community.general.homebrew:
        name: docker
        state: present

    - name: Install ZSH
      community.general.homebrew:
        name: zsh
        state: present

    - name: Install Homebrew taps
      community.general.homebrew_tap:
        name: "{{ item }}"
      loop: "{{ homebrew_taps }}"

    - name: Install Homebrew packages
      community.general.homebrew:
        name: "{{ item }}"
        state: present
      loop: "{{ envsetup_homebrew_installed_packages }}"

  post_tasks: []
