# Default env-setup playbook vars
#
# This YAML contains the list overridable variables in the env-setup playbooks.
# Copy this file to config.yml and any edited value will be used in place of 
# its default.
#
# USAGE EXAMPLE: replace the default dotfiles with your own.
# cp default.config.yml config.yml
# awk '{sub(/dotfiles_repo:.*/,"dotfiles_repo:\"https://github.com/my_github_screenname/dotfiles.git\""); print}' config.yml
# env-setup
---
downloads: ~/.ansible-downloads/

# name: env-setup.01-config ####################################################

# name: geerlingguy.dotfiles
# Find dotfiles via $(find . -type f | grep -vE '\.\/\.git\/' | sed -e 's/\.\///g')
pub_dotfiles_repo: git@github.com:ShawnConn/dotfiles.git
pub_dotfiles_repo_accept_hostkey: yes
pub_dotfiles_repo_local_destination: ~/env-setup-dotfiles
pub_dotfiles_repo_version: main
pub_dotfiles_files:
  - .bash_profile
  - .direnvrc
  - .fzf.zsh
  - .gitignore_global
  - .git_template
  - .inputrc
  - .macos
  - .notags
  - .p10k.zsh
  - .shell
  - .vim/colors/solarized.vim
  - .vimrc
  - .vundle.vimrc
  - .zshrc
# any file dir that needs to exist before dotfiles mapping
# useful when you don't want to keep an entire dir mapped to git
pub_dotfiles_subdirs: 
  - ~/.vim/colors/

# OPTIONAL FOR NON PUBLIC DOTFILES
# name: geerlingguy.dotfiles
# Find dotfiles via $(find . -type f | grep -vE '\.\/\.git\/' | sed -e 's/\.\///g')
prv_dotfiles_repo: git@github.com:ShawnConn/dotfiles-prv.git
prv_dotfiles_repo_accept_hostkey: yes
prv_dotfiles_repo_local_destination: ~/env-setup-prv-dotfiles
prv_dotfiles_repo_version: main
prv_dotfiles_files:
  - .app
  - .bitbar
  - .config
  - .fonts
  - .gitconfig
  - .gitignore
  - .index
  - .mackup.cfg
  - .npmrc
  - .projects
  - .sman-snips
  - .ssh/config
  - .templates
  - .tigrc
  - .toprc
  - .tmux.conf
  - .vim/after
  - .vim/plugin
  - .vim/dictionaries
  - .vim/templates
  - .warprc
  - .weblink

# any file dir that needs to exist before dotfiles mapping
# useful when you don't want to keep an entire dir mapped to git
prv_dotfiles_subdirs: []

# name: env-setup.02-cli-tools #################################################

# NOTE: in linux we'll use the the community.general.homebrew* modules
# name: geerlingguy.mac.homebrew
homebrew_installed_packages:
  - antigen
  - arp-scan
  - asciinema
  - autoconf
  - awslogs
  - bash-completion
  - bat
  - bfg
  - blackbox
  - brew-cask-completion
  - broot
  - btop
  - busser/tap/tftree
  #- circleci
  - clintmod/formulas/macprefs
  - cloc
  #- cloudflare/cloudflare/cloudflared
  #- cli53
  - cmake
  - colordiff
  - composer
  - coreutils
  - ctags
  - ctop
  - ddev
  - direnv
  - displayplacer
  - dive
  - dmg2img
  - dnsmasq
  - docker
  - docker-compose
  #- docker-credential-helper-ecr
  - doxygen
  - duti
  - easy-rsa
  - entr
  - eqnxio/go/github-com-kvz-json2hcl
  #- ethereum
  - exiftool
  - ffmpeg
  - figlet
  - fpp
  - fzf
  - gdrive
  - gettext
  - gh
  - gifsicle
  - gist
  - git
  - git-crypt
  - git-delta
  - git-fresh
  - git-lfs
  - gitleaks
  - go
  - gource
  - gpg
  - graphviz
  - gzip
  #- heroku/brew/heroku
  - hcl2json
  - hisbaan/tap/didyoumean
  - htop
  - httpie
  - htmlq
  - hub
  - hyperfine
  - inetutils
  - inframap
  - iperf
  #- irssi
  - jid
  - jittering/kegs/jqplay
  - jq
  - kops
  - kubectl
  - kubectx
  - kubernetes-helm
  - libevent
  - libpq
  - lnav
  - m-cli
  - mackup
  - mas
  - mcrypt
  - miller
  - moreutils
  - mp3splt
  - mtr
  - multitail
  - mysql-client
  - ncdu
  - nektos/tap/act
  - neovim
  - nmap
  - node
  - nq
  - nss
  - nvm
  - openssl
  - overmindtech/overmind/overmind-cli
  - python
  - p7zip
  - packer
  - padok-team/tap/tfautomv
  - pandoc
  - pgcli
  - pick
  - pipenv
  - prettyping
  - pre-commit
  - progress
  - pv
  - qrencode
  - rbenv
  - readline
  - redis
  - ripgrep
  - ruby
  - rust
  - shellcheck
  - shellharden
  - shfmt
  - signal-cli
  - sops
  - sox
  - sql-lint
  - sqlite
  - ssh-copy-id
  - stow
  - switchaudio-osx
  - terminal-notifier
  - terracognita
  - terraformer
  - terraform_landscape
  - terraform-docs
  - terrascan
  - tesseract
  - textql
  - tfenv
  - tfmigrate
  - tfsec
  - thefuck
  - the_silver_searcher
  - tig
  - tmate
  - tree
  - unrar
  - v
  - vim
  - w3m
  - wader/tap/fq
  - wakeonlan
  - watch
  - watchman
  - wget
  - wrk
  - xpdf
  - youtube-dl
  - zbar
  - zsh

homebrew_taps:
  - drud/ddev 
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-versions
  - riboseinc/easy-rsa

# name: env-setup.03-apps ######################################################

# name: geerlingguy.mac.homebrew
homebrew_cask_apps:
  - authy
  - aws-vault
  - 1password
  - 1password-cli
  - android-studio
  - appcleaner
  - bitbar
  - blackhole-2ch
  - caffeine
  - carbon-copy-cloner
  - chrome-devtools
  - chromedriver
  - chrome-remote-desktop-host
  - cloudflare/cloudflare/cf-terraforming
  - db-browser-for-sqlite
  - docker
  - firefox
  - flux
  - gpg-suite
  - google-chrome
  - google-cloud-sdk
  - google-drive
  - google-earth-pro
  - handbrake
  - homebrew/cask-fonts/font-hack-nerd-fonti
  - homebrew/cask-fonts/font-meslo-lg-nerd-font
  - insta360-studio
  - istat-menus
  - istumbler
  - iterm2
  - java
  - karabiner-elements
  #- keeper-password-manager
  #- keybase
  - keyboard-cleaner
  - keycastr
  - lando
  - licecap
  - musicbrainz-picard
  - mysql-utilities
  - ngrok
  #- obs
  #- obs-websocket
  - opera
  #- osxfuse
  #- paragon-vmdk-mounter
  - postico
  #- 'https://raw.githubusercontent.com/Homebrew/homebrew-cask/910f11ed2d6f2714ddb0d06eb4029f7ab9203202/Casks/phpstorm.rb'
  - qbittorrent
  - qr-journal
  - rectangle
  - rescuetime
  - rq
  - sequel-ace
  - signal
  #- skype
  - slack
  - slack-cli
  - sops
  - tor-browser
  - tunnelblick
  #- vagrant
  - virtualbox
  #- virtualbox-extension-pack
  - visual-studio-code
  - vlc
  - wireshark
  - xquartz
  - yarn
  - zoom

# name: geerlingguy.mac.mas
mas_installed_apps:
  - { id: 824183456, name: "Affinity Photo" }
  - { id: 803453959, name: "Slack" }
  - { id: 497799835, name: "Xcode" }
  - { id: 984278082, name: "Tag Editor Lite" }

mas_uninstalled_apps:
  - { id: 408981434, name: "iMovie" }
  - { id: 409183694, name: "Keynote" }
  - { id: 409201541, name: "Pages" }
  - { id: 409203825, name: "Numbers" }
  - { id: 682658836, name: "GarageBand" }

# NOTE: will need to sign to App Store
mas_email: ""
mas_password: ""

# name: geerlingguy.mac.dock
configure_dock: true

dockitems_persist:
  - name: "Signal"
    path: "/Applications/Signal.app"
    pos: 1
  - name: "Google Chrome"
    path: "/Applications/Google\ Chrome.app"
    pos: 2
  - name: "iTerm2"
    path: "/Applications/iTerm.app/"
    pos: 3
  - name: "Affinity Photo"
    path: "/Applications/Affinity Photo.app"
    pos: 4
  - name: "XCode"
    path: "/Applications/Xcode.app"
    pos: 5
  - name: "VS Code"
    path: "/Applications/Visual Studio Code.app'"
    pos: 6
  #- name: "Postico 2"
  #  path: "/Applications/Postico 2.app"
  #  pos: X
  #- name: "Sequel Ace"
  #  path: "/Applications/Sequel Ace.app"
  #  pos: X
  #- name: "App Store"
  #  path: "/System/Applications/App\ Store.app"
  #  pos: X
  #- name: "FaceTime"
  #  path: "/System/Applications/FaceTime.app"
  #  pos: X
  #- name: "Finder"
  #  path: "/System/Library/CoreServices/Finder.app"
  #  pos: X

dockitems_remove:
  - Launchpad
  - Safari
  - Messages
  - Mail
  - Maps
  - Photos
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - Freeform
  - TV
  - Music
  - Podcasts
  - News

# name: env-setup.04-packages ##################################################
cargo_packages:
  - name: bore
  - name: gitql
  - name: gret

composer_packages:
  - name: drupal/coder
  - name: drupal/console-launcher
    state: present
    version: "~1.0"
  - name: kherge/box
  - name: pdepend/pdepend
  - name: phpunit/dbunit
  - name: phpunit/phpunit
  - name: phploc/phploc
  - name: phpmd/phpmd
  - name: phing/phing
  - name: psy/psysh
  - name: sebastian/phpcpd
  - name: sebastian/phpdcd
  - name: squizlabs/php_codesniffer
  - name: techlivezheng/phpctags

go_packages:
  - name: github.com/rsc/2fa@latest
  - name: github.com/cristoper/gsheet/cmd/gsheet@latest
  - name: github.com/chriswalz/bit@latest
  - name: github.com/erroneousboat/slack-term@latest
  - name: github.com/GoogleCloudPlatform/cloud-build-local@latest
  - name: github.com/1buran/rhttp@latest
  - name: github.com/nikitavoloboev/gitupdate@latest
  - name: github.com/posener/complete/gocomplete@latest
  - name: github.com/micahhausler/k8s-oidc-helper@latest
  - name: github.com/FiloSottile/mkcert@latest
  - name: github.com/six-ddc/plow@latest
  - name: github.com/ericchiang/pup@latest
  - name: github.com/tokozedg/sman@latest
  - name: github.com/pcasteran/terraform-graph-beautifier@latest
  - name: github.com/ericchiang/xpup@latest
  - name: github.com/jacobcmurphy/word_helper_cli@latest

gem_packages:
  - name: ghi

npm_packages:
  - name: '@angular/cli'
  - name: bower
  - name: browserify
  - name: cloudflare-cli
  - name: commitizen
  - name: cz-conventional-changelog
  - name: '@cloudflare/wrangler'
  - name: eslint
  - name: fkill-cli
  - name: gatsby-cli 
  - name: github
  - name: '@google/clasp'
  - name: jsonlint
  - name: localtunnel
  - name: npmdoctor
  - name: nuxt
  - name: octonode
  - name: persistgraphql 
  - name: protractor
  - name: readability-wrapper
  - name: redis-dump
  - name: regexgen
  - name: regexgen-cli
  - name: saucectl
  - name: showdown
  - name: solhint
  - name: standard
  - name: '@storybook/cli'
  - name: typescript
  - name: '@types/react'
  - name: '@vue/cli'
  - name: yarn
  - name: zx

pip_packages:
  - name: ansible-lint
  - name: awscli
  - name: aws-shell
  - name: bashate 
  - name: boto
  - name: cheat
  - name: crudini
  - name: file-info
  - name: gcalcli
  - name: geocoder
  - name: google-music-manager-uploader
  - name: greynoise
  - name: http-prompt
  - name: html2text
  - name: jinja2-cli
  - name: jinja2-cli[xml]
  - name: jinja2-cli[yaml]
  - name: litecli
  - name: logdissect
  - name: mycli
  - name: openai
  - name: percol
  - name: pinggraph
  - name: pipdeptree
  - name: proselint
  - name: ptpython
  - name: pynvim
  - name: pylint
  - name: rackspace-novaclient
  - name: raven
  - name: repren
  - name: selenium
  - name: spotdl
  - name: swiftly
  - name: togglCli
  - name: virtualenv
  - name: vobject
  - name: whatportis
  - name: xmltodict
  - name: yq

# name: env-setup.05-repos #####################################################

git_repo_project_dir: ~/env-setup-git-repos
git_repo_projects:
  - name: env-setup
    url: git@github.com:ShawnConn/env-setup.git
    upstream: git@github.com:Luciditi/env-setup.git
    symlink: ~/Documents/Luciditi/projects/devops/env-setup

git_repo_vendors_dir: ~/env-setup-vendors
git_repo_vendors:
  - name: luciditi
    host: git@github.com
    projects:
      - name: env-setup-dotfiles
        depth: 1
