---
- name: Install Apps
  hosts: all

  vars_files:
    - ../../../default.config.yml

  pre_tasks:
    - name: Set unlimited sudo timeout
      lineinfile:
        dest: /etc/sudoers.d/ssh_session_timeout
        line: 'Defaults  env_reset,timestamp_timeout=-1'
        create: yes
        owner: root 
        group: wheel 
        mode: 0440
        state: present
        validate: 'visudo -c -f %s'
      become: yes
      tags: ["sudo"]

    - name: Open AppStore
      shell: open /System/Applications/App\ Store.app
      args:
        executable: bash
      tags: ["app_store"]

    - name: XCODE WARNING
      ansible.builtin.pause:
        prompt: "NOTE: installing XCode may cause issues w/ ansible (you may need to run `sudo xcodebuild -license` after installation in App Store)"
        seconds: 7
      when: mas_installed_apps | selectattr('name', 'equalto', 'Xcode') | list | count > 0
      tags: ["app_store"]

    - name: Confirm App Store signin
      ansible.builtin.pause:
        prompt: "Please SIGN IN to the App Store before continuing then hit ENTER...."
        echo: no
      tags: ["app_store"]

    - name: Apply macos defaults
      include_tasks: defaults.yml
      tags: ["defaults"]

  roles:
    - { role: geerlingguy.mac.homebrew, 
        homebrew_cask_apps: "{{ envsetup_homebrew_cask_apps }}",
        homebrew_installed_packages: [],
        tags: ["print_action", "apps"] }
    - { role: geerlingguy.mac.mas, 
        tags: ["print_action", "app_store"] }
    - { role: geerlingguy.mac.dock, tags: ["print_action", "dock"] }

  tasks: []
        
  post_tasks:
    - name: Check for XCode.
      raw: test -e /usr/bin/xcodebuild
      register: xcode_present
      failed_when: false
      changed_when: false
      tags: ["app_store"]

    - name: Accept XCode license
      raw: /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -license accept
      when: xcode_present.rc != 0
      become: yes
      become_method: sudo
      tags: ["app_store"]

    - name: Remove unlimited sudo timeout config
      file:
        path: /etc/sudoers.d/ssh_session_timeout
        state: absent
      become: yes
      tags: ["sudo"]

    - name: Open apps for manual configuration
      include_tasks: open.yml
      tags: ["open"]
