---
- name: Conigure OS settings
  hosts: all

  vars_files:
    - ../../../default.config.yml

  pre_tasks: []

  roles: []

  tasks:

    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ envsetup_os_hostname }}"
        
  post_tasks: []
