---
- name: Ensure duti is installed
  homebrew:
    name: duti
    state: latest

- name: Get default handlers for extensions
  command: >
    duti -x {{ item.extension }}
  register: duti_result
  with_items: "{{ envsetup_prefs_macos_file_extension_handlers }}"
  changed_when: false
  failed_when: false

- name: Set default handlers for extensions
  command: >
    duti -s {{ item.1.handler }} {{ item.1.extension }} {{ item.1.roles|default('all') }}
  with_indexed_items: "{{ envsetup_prefs_macos_file_extension_handlers }}"
  changed_when: item.1.handler not in duti_result.results[item.0].stdout
