---
- name: Install Apps
  hosts: all
  become: true

  vars_files:
    - ../../../default.config.yml

  vars:
    packages:
      # @TODO use envsetup_homebrew_cask_apps to map equivalents in linux
      # e.g., google-chrome ~~> chromium-browser
      chrome-devtools: "chromium-browser"
      chromedriver: "chromium-chromedriver"
      docker-desktop: "docker"
      docker: "docker"
      google-chrome: "chromium-browser"
      font-meslo-lg-nerd-font: "fontconfig"
      iterm2: "terminology"
      postico: "postgresql-client"
      sequel-ace: "default-mysql-client"
      tunnelblick: "openvpn"
      visual-studio-code: "vim"
      zoom: "gdebi"

  pre_tasks:
    - name: Set unlimited sudo timeout
      lineinfile:
        dest: /etc/sudoers.d/ssh_session_timeout
        line: 'Defaults  env_reset,timestamp_timeout=-1'
        create: yes
        owner: root 
        group: root 
        mode: 0440
        state: present
        validate: 'visudo -c -f %s'
      become: yes
      tags: ["sudo"]

  roles: []

  tasks:

    - name: Install configured applications
      ansible.builtin.package:
        name: "{{ packages[item] }}"
        state: present
      loop: "{{ envsetup_homebrew_cask_apps }}"
      ignore_errors: true
      tags: ["apps"]
        
  post_tasks:
    - name: Remove unlimited sudo timeout config
      file:
        path: /etc/sudoers.d/ssh_session_timeout
        state: absent
      become: yes
      tags: ["sudo"]
