name: deploy-image

env:
  ENVSETUP_REPO_SSH: ${{ github.event.inputs.repo || 'git@github.com:Luciditi/env-setup.git' }}
  ENVSETUP_DOTFILES_REPO_SSH: ${{ github.event.inputs.dotfiles_repo || 'git@github.com:Luciditi/env-setup-dotfiles.git' }}
  ENVSETUP_DOTFILES_PRV_REPO_SSH: ${{ github.event.inputs.dotfiles_prv_repo || 'git@github.com:Luciditi/env-setup-dotfiles.git' }}
  ENVSETUP_CONFIG: ${{ github.event.inputs.config || 'docker/default.config.yml' }}
  ENVSETUP_VERSION: ${{ github.event.inputs.version || '' }}
  ENVSETUP_ORG: "luciditi"

on:
  workflow_dispatch:
    inputs:
      config:
        type: choice
        description: "The configuration manifest used for running env-setup."
        options: 
          - 'docker/default.config.yml'
          - 'docker/.mini.config.yml'
          - 'docker/.most.config.yml'
          - 'docker/.none.config.yml'
        required: true
        default: 'docker/default.config.yml'
      version:
        description: "The env-setup version tag."
        required: true
        default: ''
      repo:
        description: "The default repo of `env-setup`."
        required: true
        default: 'git@github.com:Luciditi/env-setup.git'
      dotfiles_repo:
        description: "The default repo of public dotfiles."
        required: true
        default: 'git@github.com:Luciditi/env-setup-dotfiles.git'
      dotfiles_prv_repo:
        description: "The default repo of private dotfiles."
        required: true
        default: 'git@github.com:Luciditi/env-setup-dotfiles.git'
      latest:
        type: boolean
        description: "Tag as latest."
        default: false

jobs:
  build-and-deploy-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup SSH key
        run: |
          echo "$ENVSETUP_SSH_KEY" > ./.ssh_key_id_rsa
        env:
          ENVSETUP_SSH_KEY: ${{ secrets.ENVSETUP_SSH_KEY }}

      # https://docs.docker.com/build/ci/github-actions/manage-tags-labels/
      - name: Get Image Tags
        run: |
          CONFIG="${{ env.ENVSETUP_CONFIG }}"
          VERSION="${{ env.ENVSETUP_VERSION }}"
          LATEST=${{ github.event.inputs.latest }}
          case "$CONFIG" in
            "docker/default.config.yml") TAG="$VERSION-default" ;;
            "docker/.mini.config.yml") TAG="$VERSION-mini" ;;
            "docker/.most.config.yml") TAG="$VERSION-most" ;;
            "docker/.none.config.yml") TAG="$VERSION-none" ;;
            *) TAG="$VERSION" ;;
          esac
          if [[ $LATEST == "true" ]]; then
            REPO_TAGS="ghcr.io/${{ env.ENVSETUP_ORG }}/env-setup:$TAG,ghcr.io/${{ env.ENVSETUP_ORG }}/env-setup:latest"
          else
            REPO_TAGS="ghcr.io/${{ env.ENVSETUP_ORG }}/env-setup:$TAG"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "repo_tags=$REPO_TAGS" >> $GITHUB_OUTPUT
        id: get-tags

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          build-args: |
            ENVSETUP_REPO_SSH=${{ env.ENVSETUP_REPO_SSH }}
            ENVSETUP_DOTFILES_REPO_SSH=${{ env.ENVSETUP_DOTFILES_REPO_SSH }}
            ENVSETUP_DOTFILES_PRV_REPO_SSH=${{ env.ENVSETUP_DOTFILES_PRV_REPO_SSH }}
            ENVSETUP_CONFIG=${{ env.ENVSETUP_CONFIG }}
            ENVSETUP_VERSION=${{ env.ENVSETUP_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: docker/Dockerfile
          labels: |
            org.opencontainers.image.ref.name=${{ env.ENVSETUP_ORG }}/env-setup-${{ steps.get-tags.outputs.tag }}
            org.opencontainers.image.version=${{ env.ENVSETUP_VERSION }}
          platforms: linux/amd64
          push: true
          secret-files: |
            ssh=./.ssh_key_id_rsa
          tags: ${{ steps.get-tags.outputs.repo_tags }}

      #- name: Setup tmate session
        #uses: mxschmitt/action-tmate@v3
